---
- name: Setup Apache on Amazon Linux, RHEL, and Ubuntu
  hosts: apache_servers
  become: yes

  tasks:
    - name: Install Apache (httpd for Amazon Linux/RHEL, apache2 for Ubuntu)
      package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present

    - name: Start and Enable Apache Service
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

        

